# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/bq/msm8953-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bardock,$(TARGET_DEVICE)),)

endif
