# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/bq/bardockpro/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/bq/bardockpro

PRODUCT_COPY_FILES += \
    vendor/bq/bardockpro/proprietary/vendor/bin/climax_hostSW:$(TARGET_COPY_OUT_VENDOR)/bin/climax_hostSW \
    vendor/bq/bardockpro/proprietary/vendor/firmware/Tfa9896.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9896.cnt \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b00 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b01 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b02 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b03 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b04 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b05 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.b06 \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.flist:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.flist \
    vendor/bq/bardockpro/proprietary/etc/firmware/fpchips64.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fpchips64.mdt \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b00 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b01 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b02 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b03 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b04 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b05 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.b06 \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.mbn \
    vendor/bq/bardockpro/proprietary/etc/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/goodixfp.mdt \
    vendor/bq/bardockpro/proprietary/etc/firmware/ice40.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/ice40.bin \
    vendor/bq/bardockpro/proprietary/etc/firmware/ilitek_i2c.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/ilitek_i2c.bin \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b00 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b01 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b02 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b03 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b04 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b05 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.b06 \
    vendor/bq/bardockpro/proprietary/etc/firmware/sw_fp.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/sw_fp.mdt \
    vendor/bq/bardockpro/proprietary/lib64/hw/csfingerprint.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/csfingerprint.default.so \
    vendor/bq/bardockpro/proprietary/lib64/hw/fingerprint.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/fingerprint.default.so \
    vendor/bq/bardockpro/proprietary/lib64/hw/swfingerprint.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/swfingerprint.default.so \
    vendor/bq/bardockpro/proprietary/lib64/libgf_ca.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgf_ca.so \
    vendor/bq/bardockpro/proprietary/lib64/libgf_hal.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgf_hal.so \
    vendor/bq/bardockpro/proprietary/lib64/libgoodixfingerprintd_binder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgoodixfingerprintd_binder.so \
    vendor/bq/bardockpro/proprietary/vendor/etc/drc/drc_cfg_5.1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/drc/drc_cfg_5.1.txt \
    vendor/bq/bardockpro/proprietary/vendor/etc/drc/drc_cfg_AZ.txt:$(TARGET_COPY_OUT_VENDOR)/etc/drc/drc_cfg_AZ.txt \
    vendor/bq/bardockpro/proprietary/vendor/etc/surround_sound_3mic/surround_sound_rec_5.1.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/surround_sound_3mic/surround_sound_rec_5.1.cfg \
    vendor/bq/bardockpro/proprietary/vendor/etc/surround_sound_3mic/surround_sound_rec_AZ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/surround_sound_3mic/surround_sound_rec_AZ.cfg
